wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 3
      - 8
      4: 3.8.5
      5: 0.10.30
      8:
      - 5
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 3
